### ISSUE TITLE
Win scene and death scene needed

### ISSUE THREAD

**Issue by sodamachinebroke** [sodamachinebroke/penultimateDaydream#1]
Need to write a win scene, that puts the character to the same place as if you fleed.
Also need to write a death scene if the character is defeated and that should drop you back to the main menu. 

Win should have a text smth like "Lol you win"

Death should have the dark souls death text idc

**Comment by PogiAbel** [comment]
Win scene simple particle system with music
Death is a red fade over the main menu with death music
